### ISSUE TITLE
What's the diff compare to build_context package?

### ISSUE THREAD

**Issue by sooxt98** [dartsidedev/xcontext#1]

**Comment by vincevargadev** [comment]
In short, not much, as I see, both packages do similar things: they add static extension methods to the `BuildContext`.

Their approach seems to be to focus on the commonly used features and add them to the context.

My approach was to add everything to the context that is in the Flutter package and can be accessed with the `of(context)` pattern. One another thing I added is all the `showXyz(context, ...)` methods.

The way I see it, the consequences of these decisions are:
* `build_context` can provide some commonly used values as a convenient getter
* `xcontext` can be sometimes more verbose but it's more predictable (as it has a clearer rule as to what to add to the context).

There is definitely some overlap between the packages, but there are also some differences. Use whichever you like more.
